### PR TITLE
Updated snp ancestry merger module

### PR DESCRIPTION
**Pull request by lbiral**
Minor modifications to snp ancestry merger module

### CODE REVIEW

**Review by DevangThakkar — COMMENTED** [review]
Looks like we only pass the working directory so the argument `admixture_coefs` or `admixture_coefs_cleaned` isn't really being used. Is that correct?

**Comment by lbiral** [comment]
No. Tushar suggested I have it though

**Comment by DevangThakkar** [comment]
Sure, that works. Can you add comments near them that describe that? It'll be helpful in the future.

**Review by tushardave26 — COMMENTED** [review]
@lbiral - you have to set the `admixture_coefs` argument in the `define_inptut` method. You had it before, but now it is commented out. All your input files for the merger are feeding from the sample sheet. Without setting up an argument for the input file type, I believe the `Kubernetes` will not copy the input file to the `/data` directory during the execution.

@parkerc71 - can you please explain how the required input files are being copied to the `/data` dir for a given task?

**Comment by lbiral** [comment]
I commented it out as a test. It is changed now.

**Comment by DevangThakkar** [comment]
I think what I meant is the one in the command isn't required but the one in the input is. CC needs to know that it has to copy the file.

**Comment by DevangThakkar** [comment]
I might be wrong but try it with that.

**Comment by parkerc71** [comment]
> @lbiral - you have to set the `admixture_coefs` argument in the `define_inptut` method. You had it before, but now it is commented out. All your input files for the merger are feeding from the sample sheet. Without setting up an argument for the input file type, I believe the `Kubernetes` will not copy the input file to the `/data` directory during the execution.
> 
> @parkerc71 - can you please explain how the required input files are being copied to the `/data` dir for a given task?

this is all correct.

**Comment by lbiral** [comment]
Alright we are good to go

**Comment by lbiral** [comment]
Tested and it's all good

**Comment by lbiral** [comment]
Finished the test and it works.

**Review by DevangThakkar — APPROVED** [review]
LGTM

**Pull request merged**
