### PR TITLE
Manta

### PR DESCRIPTION
**Pull request by parkerc71**
Adding in Manta + Pindel + Manta/Pindel Merger module.

Also adding in a touch command on the final perms task for Kubernetes. The task will touch all index files to ensure that they are older than their respective data files.

### CODE REVIEW

**Review by tushardave26 — APPROVED** [review]
Looks good!

**Comment by DevangThakkar** [comment]
Why does the index file need to be older? Shouldn't it be newer?

**Comment by parkerc71** [comment]
Sorry, newer index files. Not older. The touch will update the date to the time it is touched, making it newer so there won't be complaints from the tool(s) on the age of the index file.

**Comment by DevangThakkar** [comment]
Cool, thanks!

**Pull request merged**
