### PR TITLE
Make Arriba UMI-Aware

### PR DESCRIPTION
**Pull request by DevangThakkar**

### CODE REVIEW

**Review by tushardave26 — CHANGES_REQUESTED** [review]
Can you please change the class name to CamelCase (e.g. STARArriba)?

**Comment by DevangThakkar** [comment]
Should I also change Arriba_UMI to ArribaUMI? What's the convention for camel case when words have all caps?

**Comment by tushardave26** [comment]
Yes, change that as well. To answer your second question, you can keep either all caps in the name or have the first letter uppercase.

**Review by tushardave26 — APPROVED** [review]
Looks good!!

**Pull request merged**
