### PR TITLE
Snp ancestry clean

### PR DESCRIPTION
**Pull request by lbiral**
Implemented features Devang recommended in 3/8/23 WHO meeting

### CODE REVIEW

**Review by DevangThakkar — CHANGES_REQUESTED** [review]
Alright, this looks mostly good. What I would like though is for us to have this utility as a separate class within the [SNPAncestry.py](https://github.com/labdave/CloudConductor/blob/master/Modules/Tools/SNPAncestry.py) file so we have only one place for two related tools.

**Comment by lbiral** [comment]
Fixing now

**Comment by lbiral** [comment]
Done. Ran on dev site and it's all good

**Review by DevangThakkar — APPROVED** [review]
LGTM

**Pull request merged**
